### ISSUE TITLE
Can someone please help me?

### ISSUE THREAD

**Issue by CCCCC96** [nbclark/hqcheat#11]
I get this problem everytime, tried to fix it but nothing! Anyone can help?

Processing...
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: bitblt reading outside image
    at Function.PNG.bitblt (/Users/apple/node_modules/pngjs/lib/png.js:121:11)
    at exports.PNG.PNG.bitblt (/Users/apple/node_modules/pngjs/lib/png.js:140:7)
    at exports.PNG.<anonymous> (/Users/apple/node_modules/png-crop/index.js:49:12)
    at exports.PNG.emit (events.js:160:13)
    at exports.PNG.<anonymous> (/Users/apple/node_modules/pngjs/lib/png.js:36:10)
    at module.exports.emit (events.js:160:13)
    at module.exports.ParserAsync._complete (/Users/apple/node_modules/pngjs/lib/parser-async.js:109:8)
    at module.exports.emit (events.js:160:13)
    at module.exports.complete (/Users/apple/node_modules/pngjs/lib/filter-parse-async.js:19:12)
    at module.exports.Filter._reverseFilterLine (/Users/apple/node_modules/pngjs/lib/filter-parse.js:169:10)

**Comment by dot-dot-dot-dot** [comment]
run `npm install pngjs`

**Comment by CCCCC96** [comment]
@AlexS-GitHub thanks for the answer but i still get the same error! Any further suggestions?
