### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by roseyg71** [nbclark/hqcheat#13]
@nbclark 
After typing in " node index.js " I get this...
`
/Users/gabe/Desktop/hqcheat-master/index.js:71
          .map(o => ({ ...o, count: occurrences(genericSearch, o.name.toLowerCase(), true) }))
                       ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
`

**Comment by D-Buz** [comment]
At this point I would just restart the setup process with a fresh copy because it's not clear what is needed... Make sure you use NPM to download all the softawre require by the js file. In terminal "npm install -p"

**Comment by todd-lm** [comment]
@D-Buz  Hey, i'm also getting this exact error, i tried doing what you said and uninstalling and re-installing npm again and starting with a new downloaded copy but i'm still getting the same error. any ideas?
Update: Do u think i might need to have xcode installed, i was in the process of installing it when i was trying this?
