### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by asolimine** [nbclark/hqcheat#6]
Hey, I've been having some trouble getting the script to work. I have downloaded all the requirements but every time I take a screen shot of the question I get this error and I'm not sure what it means. 

Processing...
Got question: 
Got options:  

(node:520) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at Promise.all.then (/Users/antoniosolimine/Desktop/hqcheat-master/index.js:84:81)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by apates5** [comment]
I am having the same problem. I think it is because the person who made it has a iphone x so the way the photo is cropped is going to be different for every different version phone. I just dont know how to change the way the picture is cropped.

**Comment by asolimine** [comment]
At first I thought that was the problem too, but I have an iphone X too and im still getting that error

**Comment by apates5** [comment]
Are you using a picture of a hq question or a prerecorded video of hq to test it?

**Comment by asolimine** [comment]
Im using a prerecorded video

**Comment by apates5** [comment]
Oh then I don’t know. I’m not sure but it might be because the quality on the video is low so it might not be clear. Or it might be that if the video has comments on it it might be interfering with it. Just some guesses I’m not sure.

**Comment by kaikuale** [comment]
Were you guys able to find a fix?

**Comment by asolimine** [comment]
Nothing yet. Sorry

**Comment by kaikuale** [comment]
Ok for me I had to edit the code that crops the image. For me personally, I just used a bit of trial and error. The numbers I manipulated will be shown below and bolded. The ones in italics should be slightly larger than your phones screen resolution.

const processImage = path => {
  const top = **400**;
  const bottom = **900**;
  const left = **150**;
  var config1 = { width: _1174_ - left - left, height: _2278_ - top - bottom, top, left };
